---
abstract: 'Constructor for clients of Clustericious apps'
author: 
  - 'Curt Tilmes <Curt.Tilmes@nasa.gov>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious-Client
provides:
  Clustericious::Client:
    file: lib/Clustericious/Client.pm
    version: 0.01
  Clustericious::Client::Command:
    file: lib/Clustericious/Client/Command.pm
  Clustericious::Client::Object:
    file: lib/Clustericious/Client/Object.pm
  Clustericious::Client::Object::DateTime:
    file: lib/Clustericious/Client/Object/DateTime.pm
  Clustericious::Client::Object::Params:
    file: lib/Clustericious/Client/Object/Params.pm
requires:
  Clustericious: 0
  JSON::XS: 0
  Mojolicious: 0.999926
version: 0.02
